NN_PROFILE_SITE = $(realpath $(TOPDIR))/package/nn_profile
NN_PROFILE_SITE_METHOD = local
NN_PROFILE_INSTALL_TARGET = YES
NN_PROFILE_SUPPORTS_IN_SOURCE_BUILD = NO
NN_PROFILE_CONF_OPTS = -DNN_PROFILE_K230_TUNING=ON

$(eval $(cmake-package))
